In [1]:
import pandas as pd

In [6]:
vn = pd.read_csv('data/banana.csv')
vn

,Unnamed: 0.1,Unnamed: 0,Product,Country,Year,Population,Production (t),production__tonnes__per_capita,Production per capita (kg),Yield (t/ha),...,other_uses__tonnes__per_capita,Other uses per capita (kg),Supply chain waste (t),waste_in_supply_chain__tonnes__per_capita,Supply chain waste per capita (kg),Food supply (kg per capita per year),Food supply (g per capita per day),Food supply (kcal per capita per day),Food supply (Protein g per capita per day),Food supply (Fat g per capita per day)
0,13482,13482,Banana,Vietnam,1961,33621980.0,360000.0,0.010707,10.707282,9.917399,...,NaN,NaN,36000.0,0.001071,1.070728,9.473511,25.954824,16.354164,0.211868,0.050445
1,13483,13483,Banana,Vietnam,1962,34533890.0,362000.0,0.010482,10.482458,9.783800,...,NaN,NaN,36000.0,0.001042,1.042454,9.240275,25.315822,15.950355,0.202416,0.050604
2,13484,13484,Banana,Vietnam,1963,35526730.0,385000.0,0.010837,10.836911,9.871799,...,NaN,NaN,39000.0,0.001098,1.097765,9.556153,26.181241,16.497793,0.212809,0.050669
3,13485,13485,Banana,Vietnam,1964,36509172.0,400000.0,0.010956,10.956151,10.000000,...,NaN,NaN,40000.0,0.001096,1.095615,9.596199,26.290956,16.562328,0.213249,0.050774
4,13486,13486,Banana,Vietnam,1965,37466076.0,410000.0,0.010943,10.943233,10.250000,...,NaN,NaN,41000.0,0.001094,1.094323,9.585793,26.262448,16.553576,0.213923,0.050934
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,13539,13539,Banana,Vietnam,2018,94914330.0,2087274.0,0.021991,21.991143,16.242400,...,NaN,NaN,175000.0,0.001844,1.843768,19.570000,53.616438,35.340000,0.450000,0.070000
58,13540,13540,Banana,Vietnam,2019,95776710.0,2194247.0,0.022910,22.910027,16.419300,...,NaN,NaN,187000.0,0.001952,1.952458,20.620003,56.493158,37.240005,0.470000,0.070000
59,13541,13541,Banana,Vietnam,2020,96648680.0,2267520.0,0.023461,23.461472,16.603400,...,NaN,NaN,184000.0,0.001904,1.903803,15.260000,41.808219,27.560000,0.350000,0.050000
60,13542,13542,Banana,Vietnam,2021,97468024.0,2348199.0,0.024092,24.091998,16.908600,...,NaN,NaN,199000.0,0.002042,2.041695,21.780003,59.671240,39.330006,0.500000,0.080000
61,13543,13543,Banana,Vietnam,2022,98186856.0,2514820.0,0.025613,25.612596,17.487799,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
vn.columns

Index(['Unnamed: 0.1', 'Unnamed: 0', 'Product', 'Country', 'Year',
       'Population', 'Production (t)', 'production__tonnes__per_capita',
       'Production per capita (kg)', 'Yield (t/ha)', 'Yield (kg/animal)',
       'Land Use (ha)', 'area_harvested__ha__per_capita',
       'Land Use per capita (m²)', 'Producing or slaughtered animals',
       'Producing or slaughtered animals per capita', 'Imports (t)',
       'imports__tonnes__per_capita', 'Imports per capita (kg)', 'Exports (t)',
       'exports__tonnes__per_capita', 'Exports per capita (kg)',
       'Domestic supply (t)', 'domestic_supply__tonnes__per_capita',
       'Domestic supply per capita (kg)', 'Food (t)',
       'food__tonnes__per_capita', 'Food per capita (kg)', 'Animal feed (t)',
       'feed__tonnes__per_capita', 'Animal feed per capita (kg)',
       'Other uses (t)', 'other_uses__tonnes__per_capita',
       'Other uses per capita (kg)', 'Supply chain waste (t)',
       'waste_in_supply_chain__tonnes__per_capita',
       'Supply chain waste per capita (kg)',
       'Food supply (kg per capita per year)',
       'Food supply (g per capita per day)',
       'Food supply (kcal per capita per day)',
       'Food supply (Protein g per capita per day)',
       'Food supply (Fat g per capita per day)'],
      dtype='object')

In [13]:
vn = vn.drop(['Unnamed: 0.1', 'Unnamed: 0','Country'],axis=1)

,Product,Year,Population,Production (t),production__tonnes__per_capita,Production per capita (kg),Yield (t/ha),Yield (kg/animal),Land Use (ha),area_harvested__ha__per_capita,...,other_uses__tonnes__per_capita,Other uses per capita (kg),Supply chain waste (t),waste_in_supply_chain__tonnes__per_capita,Supply chain waste per capita (kg),Food supply (kg per capita per year),Food supply (g per capita per day),Food supply (kcal per capita per day),Food supply (Protein g per capita per day),Food supply (Fat g per capita per day)
0,Banana,1961,33621980.0,360000.0,0.010707,10.707282,9.917399,NaN,36300.0,0.001080,...,NaN,NaN,36000.0,0.001071,1.070728,9.473511,25.954824,16.354164,0.211868,0.050445
1,Banana,1962,34533890.0,362000.0,0.010482,10.482458,9.783800,NaN,37000.0,0.001071,...,NaN,NaN,36000.0,0.001042,1.042454,9.240275,25.315822,15.950355,0.202416,0.050604
2,Banana,1963,35526730.0,385000.0,0.010837,10.836911,9.871799,NaN,39000.0,0.001098,...,NaN,NaN,39000.0,0.001098,1.097765,9.556153,26.181241,16.497793,0.212809,0.050669
3,Banana,1964,36509172.0,400000.0,0.010956,10.956151,10.000000,NaN,40000.0,0.001096,...,NaN,NaN,40000.0,0.001096,1.095615,9.596199,26.290956,16.562328,0.213249,0.050774
4,Banana,1965,37466076.0,410000.0,0.010943,10.943233,10.250000,NaN,40000.0,0.001068,...,NaN,NaN,41000.0,0.001094,1.094323,9.585793,26.262448,16.553576,0.213923,0.050934
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,Banana,2018,94914330.0,2087274.0,0.021991,21.991143,16.242400,NaN,128508.0,0.001354,...,NaN,NaN,175000.0,0.001844,1.843768,19.570000,53.616438,35.340000,0.450000,0.070000
58,Banana,2019,95776710.0,2194247.0,0.022910,22.910027,16.419300,NaN,133638.0,0.001395,...,NaN,NaN,187000.0,0.001952,1.952458,20.620003,56.493158,37.240005,0.470000,0.070000
59,Banana,2020,96648680.0,2267520.0,0.023461,23.461472,16.603400,NaN,136569.0,0.001413,...,NaN,NaN,184000.0,0.001904,1.903803,15.260000,41.808219,27.560000,0.350000,0.050000
60,Banana,2021,97468024.0,2348199.0,0.024092,24.091998,16.908600,NaN,138876.0,0.001425,...,NaN,NaN,199000.0,0.002042,2.041695,21.780003,59.671240,39.330006,0.500000,0.080000
61,Banana,2022,98186856.0,2514820.0,0.025613,25.612596,17.487799,NaN,143804.0,0.001465,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
vn.to_csv('data/banana.csv')